// Dependency-free bundling ONLY for double-click/file:// browsers that block ESM.
// Native modules remain the source of truth and are loaded directly over HTTP.
import { readFileSync, writeFileSync } from 'node:fs';
const modules = ['games', 'storage', 'engine', 'trajectory', 'dataset', 'classifier', 'vision', 'app'];
const source = modules.map(name => readFileSync(new URL(`../js/${name}.js`, import.meta.url), 'utf8').replace(/^import .+;\r?\n/gm, '').replace(/^export /gm, '').replaceAll("new URL('../', import.meta.url)", 'document.baseURI')).join('\n');
writeFileSync(new URL('../js/app.bundle.js', import.meta.url), `// Generated by node scripts/build.js. Do not edit.\n(() => {\n'use strict';\n${source}\n})();\n`);
